### ISSUE TITLE
Data fields for sheet music

### ISSUE THREAD

**Issue by jacksonargo** [virtual-vgo/vvgo#11]
What data do we want to collect for sheet music?
What questions will we be asking about sheet music?

**Comment by Ranzha** [comment]
There are a few things to consider here.

For reference, MuseScore ver 3.4.2 supports the following tags in its "Score Properties":
arranger, composer, copyright, creationDate, lyricist, movementNumber, movementTitle, platform, poet, source, translator, workNumber, workTitle.

Seems we need the following:
- **project** ("01-snake-eater"). Only current projects should be selectable from the upload form. A dropdown menu would be enough. This wouldn't be posted on /sheets, nor publicly queriable in the /sheets searchbar.
- **work-title** ("Snake Eater"). This would be tied (somehow) to the project, displayed on /sheets, and queriable by users in the searchbar.
- **sources** ("Metal Gear Solid 3"). Projects may have content from multiple sources, e.g. a Pokémon medley. These would be displayed on /sheets as a comma-separated list.
- **composers**. Same deal as with sources, projects can have multiple composers. Not visible from /sheets, but must be included on music PDFs.
- **arrangers**. Note that uploaders must include preferred names for credited arrangers where available. Not visible from /sheets, but must be included on music PDFs.
- **revision** using something standardized. I prefer date-time revision tracking with ISO 8601, but am open to other ideas.
- **part-name**. Standardized tags could be "Score", "Alto Sax", "Euphonium (T.C.)", "Guitar (TAB)". Percussion parts would simply be labelled as "Percussion".
- **part-number**. These would be positive integers. Note that a single PDF may include multiple parts on it (e.g. "Horns 1 & 3"). Dealing with this may be a pain.

Additional things to consider:
- **Contributor tags: editors, transcribers, preparers, clix-by, reviewers, addl-content-by, lyricists**. These could be added by the user via a comma-separated list. Here's where everyone gets their credit! This allows us to easily find who to consult if questions are raised about the music.

**Comment by 0az** [comment]
Sample metadata format, non-normative draft.

```toml
[[project]]
id = "01-snake-eater"
title = "Snake Eater"
sources = ["Metal Gear Solid 3"]
composers = ["Hibino, Norihiko"]
arrangers = ["Doe, Jane", "Smith, John"]
revision = 2020-04-05T21:44:50+00:00

[[project]]
id = "02-fude-pen"
title = "Fude Pen ~Ball Pen~"
sources = ["K-ON!"]
composers = ["Kyakkoku, Hajime"]
arrangers = [""]
revision = 2020-04-05T21:48:50-00:00

[[project]]
id = "03-snow-halation"
title = "Snow Halation"
sources = ["Love Live! School idol project"]
composers = ["Yamada, Takahiro", "Hata, Aki"]
arrangers = ["Nakanishi, Ryousuke"]
revision = 2020-04-05T21:58:50-00:00
```

**Comment by 0az** [comment]
Sample sheet metadata format, non-normative draft.

```toml
[[sheet]]
project = "01-snake-eater"
part-numbers = 1
part-name = ["percussion", "snare drum", "bass drum", "tam-tam"]

[[sheet]]
project = "01-snake-eater"
part-numbers = 2
part-name = "percussion"
instruments = ["tambourine", "bongos", "triangle"]

[[sheet]]
project = "02-fude-pen"
part-numbers = 1
part-name = "guitar and vocals"
instruments = ["guitar", "vocals"]

[[sheet]]
project = "02-fude-pen"
part-numbers = 1
part-name = "bass and vocals"
instruments = ["bass", "vocals"]

[[sheet]]
project = "02-fude-pen"
part-numbers = 1
part-name = "drums"
instruments = ["drums"]

[[sheet]]
project = "02-fude-pen"
part-numbers = 1
part-name = "keyboard"
instruments = ["keyboard"]
```
